name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Zip Lambda function code
        run: zip -r function.zip .  # Adjust as needed (e.g., only your handler)

      - name: Create or Update Lambda
        run: |
          FUNCTION_NAME="etl-lambda"
          ROLE_ARN="arn:aws:iam::717174411815:role/service-role/MyFirstLambdaFunction-role-5kqtw592" 
          
          # Check if function exists
          if aws lambda get-function --function-name "$FUNCTION_NAME" > /dev/null 2>&1; then
            echo "Function exists, updating..."
            aws lambda update-function-code \
              --function-name "$FUNCTION_NAME" \
              --zip-file fileb://function.zip
          else
            echo "Function does not exist, creating..."
            aws lambda create-function \
              --function-name "$FUNCTION_NAME" \
              --runtime python3.12 \                    # Change runtime as needed
              --role "$ROLE_ARN" \
              --handler lambda_function.lambda_handler \ # Change handler if different
              --zip-file fileb://function.zip
          fi

