name: Run PySpark Job

on:
  push:
    branches:
      - main

jobs:
  run-pyspark:
    runs-on: ubuntu-latest
    env:
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.18

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspark==3.3.2
          pip install -r requirements.txt
          pip install pymongo
          pip install kafka-python
          
      - name: Run PySpark job
        run: |
           spark-submit --packages org.mongodb.spark:mongo-spark-connector_2.12:10.1.1 kafamongodbwrite.py
