name: PySpark CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pyspark faker

      - name: Run PySpark job
        run: |
          python job.py

      - name: Upload partitioned output
        uses: actions/upload-artifact@v3
        with:
          name: employees-output
          path: output/employees/

              