name: PySpark CI/CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write  # allow workflow to push commits
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pyspark faker

      - name: Run PySpark job
        run: |
          python  my_email_traverse.py

      